### ISSUE TITLE
Implement edit and delete objectives

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#15]
## Value Proposition

**As a** user
**I want to** see button `edit` on objective detail
**so that** I can edit, archive and delete an objective
​

## Description

- Edit button brings user to edit view of objectives
- Archive button can be clicked and toggles
- Delete button on edit view to delete objective
- Back button is shown on edit view which discards the changes

<img width="170" alt="image" src="https://user-images.githubusercontent.com/122455254/226967027-c996c5f2-557e-4276-9d91-425accedb16d.png">

## Acceptance Criteria

- [x] Deleting objective is possible and brings user to `/home`
- [x] Editing objective name / description is possible
- [x] Archive toggle is working
- [x] Back button discard changes and brings user back to objective detail      ​

## Tasks

- [x] Add `edit` button in objective detail view
- [x] Create objective edit view as per scribble
- [x] Implement delete functionality
- [x] Implement toggle archive functionality
      ​

## Complexity

L

**Comment by Lutz-Dietterich** [comment]
LGTM
