### ISSUE TITLE
Add empty state

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#16]
## Value Proposition

**As a** user
**I want to** see empty states
**so that** I know where no item is shown yet
​

## Description

Shows some test "No item given yet..." where no item is shown
​

## Acceptance Criteria

- [x] Shows empty state on `/home` if no competitions are given
- [x] Shows empty state on `competition-detail` if no games are given
      ​

## Tasks

- [x] Create empty state component
- [x] Add empty state to competition detail game list
- [x] Add empty state to home for competitions
      ​

## Complexity

S
