### ISSUE TITLE
Implement create, edit and delete challenges

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#18]
## Value Proposition

**As a** user
**I want to** see, create, edit and delete options 
**so that** I have full control on my objectives
​

## Description

- `Challenges summary on objective card` is shown as per individual challenge details
- `Add` button on objective detail
- `Creating and editing challenges` to be implemented
- `Challenges list` on objective detail
- `Challenge detail view` as per scribble + `delete button` and corresponding functionality
​

## Acceptance Criteria

- [x] `Challenges summary on objective card` are correctly shown
- [x] Challenge `create and edit` to be working, bringing user back to objective overview after submit
- [x] Deleting challenges is possible and brings user back to Objective overview
- [x] not possible to enter a higher number in `times completed than in times needed`
      ​

## Tasks

- [x] Create `Add` button on objective detail
- [x] Add `CreateChallenge` view with functionality
- [x] Add delete challenge functionality
- [x] Add local Storage so competitions and objectives are saved
- [x] Add tests for challenges
      ​

## Complexity

L

**Comment by Lutz-Dietterich** [comment]
LGTM
