### ISSUE TITLE
Implement navigation and Archive page

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#19]
## Value Proposition

**As a** user
**I want to** see navigation bar
**so that** I can switch between `/home` and `/archive` and see active/archived items
​

## Description

- navigation without `Tactics`
- default page `/home`
- Update `/home` that only `not-archived` objectives and competitions are shown

<img width="336" alt="image" src="https://user-images.githubusercontent.com/122455254/227217164-2d66620f-780f-46d2-98d8-b05bad8e1d99.png">

- `Archive`shows cards for competition and objectives with how many items are there which are archived, detail view renders list of items
​
<img width="318" alt="image" src="https://user-images.githubusercontent.com/122455254/227220745-656f529e-e761-45bf-85a5-8355d63a46f5.png">

## Acceptance Criteria

- [x] Navigation is shown and links are working
- [x] not archived objectives and competitions are shown on home
- [x] archived objectives and competitions are shown on archive
      ​

## Tasks

- [x] Create navigation with functionality
- [x] update functionality on home for rendering items
- [x] Create archive cards
- [x] Create list in corresponding archive item
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by Lutz-Dietterich** [comment]
lacks complexity the rest looks fine to me
