### ISSUE TITLE
Add header and navigation component

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#2]
## Value Proposition

**As a** user 
**I want to** see a header bar with the app name and footer navigation
**so that** I know the name of the app and can navigate between the three main pages.
​
## Description

- header bar shows app name which is not confirmed yet, will use `FUT 23 Tracker` for now
- navigation shows three items `Home, Tactics & Archive` - `Home` to be the default homepage of the app
- click the navigation items needs to bring the user to the corresponding page 
- **no** major styles will be applied
- **no** actual content will be shown on each of the pages
​
![image](https://user-images.githubusercontent.com/122455254/225442668-20703aef-141c-4b59-9de8-a61f352d63bb.png)

## Acceptance Criteria

- [ ] header is shown
- [ ] navigation is shown
- [ ] default page of the app is `Home`
- [ ] clicking the navigation links brings user to the corresponding page
      ​

## Tasks

- [ ] implement header component that is rendered on **all** pages of the app
- [ ] implement navigation component that is rendered on **all** pages of the app
- [ ] add three main pages with slugs `/` -> Home / `/tactics` -> Tactics / `/archive` -> Archive
- [ ] add some headline (or similar) to each page
      ​

## Complexity

S
