### ISSUE TITLE
Add Tactics to navigation

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#20]
## Value Proposition

**As a** user
**I want to** see item tactics
**so that** I can visit tactics page
​

## Description

- shows item tactics as navigation point
​

## Acceptance Criteria

- [ ] shows item tactics as navigation point
- [ ] tactics can be clicked and page visited
      ​

## Tasks

- [ ] add navigation item with link
      ​

## Complexity

XS
