### ISSUE TITLE
Implement create and view tactics

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#21]
## Value Proposition

**As a** user
**I want to** visit page `tactitcs`
**so that** I can see my tactics 
​

## Description

- Name missing on scribble
- Create view will look different

<img width="179" alt="image" src="https://user-images.githubusercontent.com/122455254/227229832-3162e3c9-f666-4823-8160-545858acab2a.png">

​- possible to show more or hide, by default hidden
- switching between general and player instructions possible

<img width="191" alt="image" src="https://user-images.githubusercontent.com/122455254/227230104-e0bd3bf8-d587-46e6-9f4c-991e4af7b476.png">

## Acceptance Criteria

- [x] Creating new tactics possible
- [x] Card for each tactic is shown on list
- [x] Tactics details can be viewed
      ​

## Tasks

- [x] Create `tactics card` for list
- [x] Create `Create tactic view`
- [x] Create `tactics details view`
      ​

## Complexity

L
