### ISSUE TITLE
Implement edit and delete tactics

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#22]
## Value Proposition

**As a** user
**I want to** see edit and delete options
**so that** I can modify my tactics
​

## Description

- Edit option for name missing, will be included
-  all different instructions which can be edited are expanded
<img width="214" alt="image" src="https://user-images.githubusercontent.com/122455254/227236070-5c2579b5-91a8-43a7-86f0-2d2fd6390ea1.png">

## Acceptance Criteria

- [x] Editing and saving information is possible
- [x] Delete removes tactic and brings user back to tactics overview
      ​

## Tasks

- [x] Implement `edit` view
- [x] Implement update functionality
- [x] Implement delete functionality
      ​

## Complexity
L
