### ISSUE TITLE
Implement archive functionality for tactics

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#23]
## Value Proposition

**As a** user
**I want to** be able to archive tactics
**so that** I can check for current ones 
​

## Description

- Archive toggle defines where tactic should be shown - tactics or at archive item
​

## Acceptance Criteria

- [x] Archive button is shown and can be toggled
- [x] not archived tactics are shown on tactics and archived tactics can be found at archive
      ​

## Tasks

- [x] add archive button
- [x] add tactics archive card
- [x] update logic which tactics should be shown based on archive information
      ​

## Complexity

M

**Comment by reyk-zepper** [comment]
yezzz...it workzzz🤪...i think...two or three qa here more and i start to think about to play fifa🤓
