### ISSUE TITLE
Add competition card component

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#3]
## Value Proposition

**As a** User
**I want to** see a competition card
**so that** I can see quickly the details of my current competition(s)
​

## Description

Card shows...
 - competition name
 - competition record - no draws available / needed
 - remaining games of the competition
 - shows button to get to detail page
 - **no** major designs will be applied
 - **no** progress indicator will be shown

![image](https://user-images.githubusercontent.com/122455254/225555953-b13640ff-d9a3-48c4-9b0e-847c7123f3cc.png)

## Acceptance Criteria

- [x] Card is shown
- [x] card details `competition name, record (loses & wins), remaining games & button` are shown
      ​

## Tasks

- [x] Create `ComepetitionCard` component
- [x] Add card component to homepage
- [x] Create competition sample data

![Image](https://user-images.githubusercontent.com/122455254/225884491-cf9ce38b-ea35-4af3-8039-60f0794be0e6.png)
      ​

## Complexity

S
