### ISSUE TITLE
Implement design

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#31]
## Value Proposition

**As a** user
**I want to** see a proper design
**so that** I can already tell by it how the app is working
​

## Description

Colors to be added to the app, links and buttons be styled to help the user with the usage of the app.
These colors will be used:

![image](https://user-images.githubusercontent.com/122455254/229308128-4a97f765-4e44-4107-ba58-53dbeebe1641.png)

Additionally, icons will be added to navigation.

## Acceptance Criteria

- [ ] Proper design is shown
- [ ] all spaces are evenly in the app
- [ ] Text is not exceeding any edges
      ​

## Tasks

- [ ] research nav bar design
- [ ] research general design 
- [ ] Implement truncating text on several places to avoid creating different spaces
- [ ] Add colors as styling variables
      ​

## Complexity

L
