### ISSUE TITLE
Enhance UX

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#32]
## Value Proposition

**As a** user
**I want to** see a different functionality and design
**so that** I can use the app better
​

## Description

1. Instead of input on `edit / create game detail` show buttons to change the score:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/122455254/229310510-1ada07e2-9eab-47c2-aec6-c73520f4971d.png">

2. Quick edit option on objective ​overview with progress indicator
<img width="491" alt="image" src="https://user-images.githubusercontent.com/122455254/229311098-8e7c1bc8-03b6-4a39-914f-bac5f3ae1f07.png">

3. Descriptions to quickly tell user how a certain page is working.

4. success and error messages with create, update, delete, archive, etc. information

5. Show scale instead of input on edit general instructions
![image](https://user-images.githubusercontent.com/122455254/229810812-40db4f3c-23a7-4de2-baf7-d34253db1ac2.png)

## Acceptance Criteria

- [x] new functionalities are shown like on the scribble and working (score and xGoals can be changed, progress on challenge can be updated on objective overview, scale is shown on tactic edit and sllows to change number)
- [x] texts are added which give a hint on some pages 
- [x] success / error messages are shown on submit / change
      ​

## Tasks

- [x] Research on success / error message
- [x] Implement success / error message as component
- [x] Update edit / create game functionality
- [x] Enhance challenge overview and add quick edit with progress indicator
- [x] Check which pages need additional information and add information to it as `pageDescription` component (or similar name)
      ​

## Complexity

XL

**Comment by NinaBusz** [comment]
nice and detailed :)

**Comment by Stephan-mit-Ph** [comment]
really cool 😎
