### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#38]
## Value Proposition

**As a** user
**I want to** see progress bars on `challenges` and `objectives`
**so that** I have visual presentation of my progress
​

## Description

![image](https://user-images.githubusercontent.com/122455254/231180951-dfe393ac-2ba5-4273-8384-2498fbce5a0d.png)

-> to be shown for challenges on `objective detail`
-> to be shown for objectives on `objective detail` and `objective card on home`

## Acceptance Criteria

- [x] Progress bar is shown on each objective card and detail and on each challenge in challenge list on objective detail
- [x] Shows the challenge progress of an individual challenge and updates when challenge is updated
- [x] Shows the objective progress based on the challenges completed
- [x] Progress bar to be filled in color based on the percentage the challenge or the challenges of the objective has been completed -> 1 / 4 completed means progress bar to be filled to 25% from left to right
- [x] If no challenge has been been added to an objective and therefore not been completed, bar should be empty and not filled
      ​

## Tasks

- [x] Create progress bar component that takes to parameter `1. times the item needs to be completed and 2. times the item was completed`
- [x] Add the progress bar to objective detail and challenge list item
- [x] Write test for progress for both cases - used for objective and used for challenge
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by toshydev** [comment]
LGTM! ✅
