### ISSUE TITLE
Add last games overview

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#39]
## Value Proposition

**As a** user
**I want to** see an overview of my last results of a competition
**so that** I can quickly visually see my performance in the last games
​

## Description

![image](https://user-images.githubusercontent.com/122455254/231185623-173bbfc3-c6db-44b3-944a-e56dab45dc15.png)
​-> to be shown on competition card like this on home

![image](https://user-images.githubusercontent.com/122455254/231186225-a7e02100-c47e-4777-b608-cd3c6bd09770.png)
-> to be shown like (same way pretty much) on competition detail

## Acceptance Criteria

- [x] Shows empty state `No games tracked` if no games are added to competition
- [x] Shows results of max. last five games
- [x] Wins to show green background, defeats to show red background
- [x] Frames to be rendered from left to right
- [x] If games are updated or deleted, game overview to be correctly updated
      ​

## Tasks

- [x] create games overview component
- [x] add games overview component to competition card and detail
- [x] Write tests to check for correct number of games to be rendered and correct games (last 5) are rendered
      ​

## Complexity

L
