### ISSUE TITLE
Implement game detail page along with create & edit game functionality 

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#5]
## Value Proposition

**As a** user
**I want to** be able to create (track) new games and edit existing games on a competition
**so that** I can track games and edit details of my competition

## Description

Information / actions
- Shows the current game count (game number)
- enter the score of the game
- enter the xGoals of the game
- save / update game
- delete game
- go back to competition

![image](https://user-images.githubusercontent.com/122455254/225628884-864b754c-3977-4d4f-ba1e-a56ffcce5a7c.png)​

## Acceptance Criteria

- [x] Does not allow tracking games when no games are remaining
- [x] shows correct record on competition overview
- [x] shows correct number of remaining games
- [x] allows editing existing games
- [x] Shows game number correctly on detail page
- [x] Can not enter negative number in any input
- [x] Only allows `integers (whole numbers)` for score
- [x] Allows not whole numbers in `xGoals input`
- [x] Allows deleting games
- [x] Clicking `back` brings user back to competition
- [x] Allows saving / updating games which brings user back to competition
      ​

## Tasks

- [x] Create game detail page with corresponding buttons and inputs
- [x] Add functionality to bring user from edit button (on competition) to existing game
- [x] Add functionality to bring user from track game button (on competition) to new game
- [x] Implement function to show/update record
- [x] Implement function to show/update remaining games
- [x] implement functionality to delete existing game
- [x] implement functionality to save / update game
      ​

## Complexity

M
