### ISSUE TITLE
Implement creating new competition

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#6]
## Value Proposition

**As a** user
**I want to** to click `Create` button
**so that** I can create a new competition
​

## Description

- `Page with competitions` needs to show `Create` button
- show details/fields as per screenshot EXCEPT `type` (TBD if needed at all) and `buttons Archive and Delete`

<img width="278" alt="image" src="https://user-images.githubusercontent.com/122455254/225737321-8278ca0e-2b82-4175-9497-5547d805aff9.png">

​

## Acceptance Criteria

- [x] Create button button brings user to create competition details
- [x] After create brings user back to listing
- [x] new created competitions are shown on listing
      ​

## Tasks

- [x] Add create button
- [x] Add page to enter competition details
- [x] Add logic to show new competitions in listing
      ​

## Complexity

M
