### ISSUE TITLE
Implement edit competition details

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#7]
## Value Proposition

**As a** user
**I want to** click the edit button on competition detail
**so that** I can edit the competition details
​

## Description

- Implement functionality for edit button on competition detail
- Edit details page is shown, similar to create
- Edit details page shows buttons Archive and Delete a competition
- Shows button to Update details

![Image](https://user-images.githubusercontent.com/122455254/226565940-922c81ab-2f8e-45c7-94ef-51b6b3f68177.png)

## Acceptance Criteria

- [x] Edit button brings user to edit page
- [x] Delete button brings user to list and deletes entire competition
- [x] Archive button can be clicked
- [x] Changing game number does not allow less games than already added 
      ​

## Tasks

- [x] Create edit page
- [x] Add delete with redirect functionality
- [x] Implement `isArchived` toggle functionality
- [x] Update saves changes 
      ​

## Complexity

M
