### ISSUE TITLE
Create objective card

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/capstone-project#8]
## Value Proposition

**As a** user
**I want to** see objective cards
**so that** I can quickly see the progress of my objectives
​

## Description

- shows information as per screenshot
- shown underneath competition card(s) if given

<img width="172" alt="image" src="https://user-images.githubusercontent.com/122455254/225892420-ab9b1535-4a06-400f-8d01-7483c52ea3bb.png">
​

## Acceptance Criteria

- [ ] Shows information as per screenshot - button not clickable yet and without progress indicator
- [ ] Shown underneath competition card if given

## Tasks

- [ ] Create objective sample data
- [ ] Create objective card

<img width="485" alt="image" src="https://user-images.githubusercontent.com/122455254/225896009-86633150-ad85-4f8c-a05a-19188e3312f1.png">

## Complexity

S
